# Generated by Django 5.0.4 on 2024-04-13 09:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them_mail', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body_mail', models.CharField(max_length=500, verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='PeriodMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_period', models.CharField(max_length=150, verbose_name='Название периода')),
            ],
            options={
                'verbose_name': 'период',
                'verbose_name_plural': 'периоды',
            },
        ),
        migrations.CreateModel(
            name='StatusMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=150, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'статус рассылки',
                'verbose_name_plural': 'статусы рассылки',
            },
        ),
        migrations.CreateModel(
            name='StatusTryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=150, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'статус попытки',
                'verbose_name_plural': 'статусы попытки',
            },
        ),
        migrations.CreateModel(
            name='MailingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_mailing', models.DateTimeField(default=datetime.date(2024, 4, 13), verbose_name='Дата первой рассылки')),
                ('client_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='Клиент')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='Сообщение')),
                ('period_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.periodmailing', verbose_name='Периодичность')),
                ('status_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.statusmailing', verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='TryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_try', models.DateTimeField(default=datetime.date(2024, 4, 13), verbose_name='Дата последней попытки')),
                ('answer_postmail', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ почтового сервера')),
                ('status_try', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.statustrymailing', verbose_name='Статус попытки')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
    ]
