# Generated by Django 5.0.4 on 2024-04-13 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingconfig',
            name='period_mailing',
        ),
        migrations.RemoveField(
            model_name='mailingconfig',
            name='status_mailing',
        ),
        migrations.AlterField(
            model_name='trymailing',
            name='status_try',
            field=models.CharField(max_length=50, verbose_name='Статус попытки'),
        ),
        migrations.AlterModelOptions(
            name='mailingconfig',
            options={'permissions': [('set_is_active', 'активация рассылки')], 'verbose_name': 'настройка', 'verbose_name_plural': 'настройки'},
        ),
        migrations.RemoveField(
            model_name='mailingconfig',
            name='client_mailing',
        ),
        migrations.RemoveField(
            model_name='mailingconfig',
            name='date_first_mailing',
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Кому (клиенты сервиса)'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='date_next',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая дата рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активация рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='name',
            field=models.CharField(default='Рассылка', max_length=100, verbose_name='Название рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='period',
            field=models.CharField(choices=[('per_day', 'раз в день'), ('per_week', 'раз в неделю'), ('per_month', 'раз в месяц')], default='per_day', max_length=30, verbose_name='Периодичность рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время рассылки'),
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='status',
            field=models.CharField(choices=[('create', 'создана'), ('complete', 'завершена'), ('extend', 'запущена')], default='create', max_length=30, verbose_name='Статус рассылки'),
        ),
        migrations.AddField(
            model_name='trymailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingconfig', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='body_mail',
            field=models.TextField(blank=True, null=True, verbose_name='Тело письма'),
        ),
        migrations.AlterField(
            model_name='trymailing',
            name='answer_postmail',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='trymailing',
            name='date_last_try',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней попытки'),
        ),
        migrations.DeleteModel(
            name='PeriodMailing',
        ),
        migrations.DeleteModel(
            name='StatusMailing',
        ),
        migrations.DeleteModel(
            name='StatusTryMailing',
        ),
    ]
